### ISSUE TITLE
New repo for the Stateful Datatable Demo

### ISSUE THREAD

**Issue by majeed-hm** [axonivy-market/market-product#18]
Hi @alexsuter , hi @ivy-rew ,

can you please create the new repo for the Stateful Datatable Demo?
[TG-1588](https://axonivy.atlassian.net/browse/TG-1588)

Best regards,
Majed.

**Comment by alexsuter** [comment]
Hello @majeed-hm 

What is this demo exactly about? Seems that this to show the jsf datatable?

**Comment by majeed-hm** [comment]
Yes a JSF table with Stateful capability 
![image](https://user-images.githubusercontent.com/23138636/195046695-b9538b7b-5762-4242-be81-a10655555ffd.png)
you can finde the repo here: https://github.com/majeed-hm/stateful-datatable

**Comment by alexsuter** [comment]
I'm not sure if this needs an own entry in market or if they would better placed in html dialog demos?

what do you think? @ivy-bb @andreasbalsiger

**Comment by ivy-bb** [comment]
I would prefer to have it as an additional Demo artefact in the market seperated from the Dialog Demo that we maintain.

**Comment by alexsuter** [comment]
@majeed-hm I can not make a fork of your repository in axon ivy market, because you have forked market-product which is wrong, you should have used that as template.

I recommend to create a new repo in your name (stateful-datatable-demo) and put all of this repo in the repo so that i can make a fork.

I'll call the repo stateful-datatable-demo, because it's just a demo.
